language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_script:
script:
  - lerna run prepublishOnly --stream
after_success:
install:
  - lerna bootstrsp
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
