language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
before_script:
script:
  - npm run prepublishOnly
after_success:
install:
  - npm prune
  - npm install
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
